name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest

      - name: Run Build Script
        run: |
          cd lxdapi
          chmod +x build.sh
          ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: lxdapi/release/*.tar.gz
